import type { ItemFormValues } from "@/components/supplies/item-form";
import type { SupplyItemDetail } from "@/lib/queries/supply-items";

/** Blank defaults for a new item. */
export function emptyItemForm(): ItemFormValues {
  return {
    code: "",
    description: "",
    shortName: "",
    unit: "",
    category: "",
    brand: "",
    model: "",
    barcode: "",
    ncm: "",
    manufacturerCode: "",
    type: "MATERIAL",
    nature: "OWN",
    controlsStock: true,
    controlsLot: false,
    controlsValidity: false,
    individualControl: false,
    canSell: false,
    canRent: false,
    canReserve: true,
    requiresCalibration: false,
    requiresMaintenance: false,
    critical: false,
    supplierId: "",
    leadTimeDays: "",
    minStock: "",
    maxStock: "",
    reorderPoint: "",
    lastCost: "",
    avgCost: "",
    salePrice: "",
    rentPrice: "",
    costCenter: "",
    defaultWarehouse: "",
    location: "",
    shelf: "",
    weight: "",
    dimensions: "",
    hazardous: false,
    logisticsNotes: "",
    calibrationPeriodMonths: "",
    maintenancePeriodMonths: "",
    warningDays: "",
    measurementRange: "",
    resolution: "",
    notes: "",
    active: true,
  };
}

const str = (v: string | null) => v ?? "";
const num = (v: number | null) => (v == null ? "" : String(v));

/** Map a stored item to the form's string/boolean shape. */
export function itemToForm(item: SupplyItemDetail): ItemFormValues {
  return {
    code: str(item.code),
    description: item.description,
    shortName: str(item.shortName),
    unit: str(item.unit),
    category: str(item.category),
    brand: str(item.brand),
    model: str(item.model),
    barcode: str(item.barcode),
    ncm: str(item.ncm),
    manufacturerCode: str(item.manufacturerCode),
    type: item.type,
    nature: item.nature,
    controlsStock: item.controlsStock,
    controlsLot: item.controlsLot,
    controlsValidity: item.controlsValidity,
    individualControl: item.individualControl,
    canSell: item.canSell,
    canRent: item.canRent,
    canReserve: item.canReserve,
    requiresCalibration: item.requiresCalibration,
    requiresMaintenance: item.requiresMaintenance,
    critical: item.critical,
    supplierId: str(item.supplierId),
    leadTimeDays: num(item.leadTimeDays),
    minStock: num(item.minStock),
    maxStock: num(item.maxStock),
    reorderPoint: num(item.reorderPoint),
    lastCost: num(item.lastCost),
    avgCost: num(item.avgCost),
    salePrice: num(item.salePrice),
    rentPrice: num(item.rentPrice),
    costCenter: str(item.costCenter),
    defaultWarehouse: str(item.defaultWarehouse),
    location: str(item.location),
    shelf: str(item.shelf),
    weight: num(item.weight),
    dimensions: str(item.dimensions),
    hazardous: item.hazardous,
    logisticsNotes: str(item.logisticsNotes),
    calibrationPeriodMonths: num(item.calibrationPeriodMonths),
    maintenancePeriodMonths: num(item.maintenancePeriodMonths),
    warningDays: num(item.warningDays),
    measurementRange: str(item.measurementRange),
    resolution: str(item.resolution),
    notes: str(item.notes),
    active: item.active,
  };
}
